### ISSUE TITLE
initctl: Unable to connect to Upstart - Shippable Node v6.3.4

### ISSUE THREAD

**Issue by gegere** [Shippable/node#403]
Trying to install the new Shippable Node v6.3.4

```
# 14:13:49 #######################################
# Removing existing reqKick services...
##################################################
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
```
It looks like **upstart** is similair to **systemd**?

Any help would be great, Googled for about an hour and didn't find anything worth while...

**Comment by a-murphy** [comment]
Is the script running on Ubuntu 14.04, Ubuntu 16.04 or Centos 7?  The `upstart` commands should only be used on an Ubuntu 14.04 node, so it may be that the wrong operating system was selected when you added the node.  Does the "operating system" in the node pool match what you are trying to initialize?

**Comment by gegere** [comment]
```
uname -a
Linux PE-R710 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

**Comment by a-murphy** [comment]
It sounds like you must have an Ubuntu 14.04 BYON node pool to which you are trying to add a Ubuntu 16.04 node.  All nodes in a node pool are expected to have the same operating system, so you will need to add an Ubuntu 16.04 node pool to use Ubuntu 16.04 nodes.  Directions to create a new node pool are [here](http://docs.shippable.com/platform/management/subscription/node-pools/).  You may also need to change/add the licenses your subscription has to be able to allocate nodes to the 16.04 node pool; directions to add/remove licenses are [here](http://docs.shippable.com/platform/management/subscription/billing/).

**Comment by gegere** [comment]
This is the solution and options I was looking for.
